import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronDown, Clock3, Headphones, Menu, MoreHorizontal, Pause, Play, Search, SkipBack, SkipForward, Volume2, X } from 'lucide-react';

type Song = { id: number; title: string; artist: string; category: string; duration: string; color: string; youtubeVideoId: string };
type YouTubePlayer = { loadVideoById: (id: string) => void; loadPlaylist: (playlist: string | { list: string; listType: 'playlist' }) => void; nextVideo: () => void; previousVideo: () => void; playVideo: () => void; pauseVideo: () => void; seekTo: (seconds: number, allowSeekAhead: boolean) => void; getCurrentTime: () => number; getDuration: () => number; getVideoData: () => { title: string; author: string; video_id: string }; getPlaylist: () => string[]; getPlaylistIndex: () => number; setVolume: (volume: number) => void; destroy: () => void };
declare global { interface Window { YT?: { Player: new (target: string, options: object) => YouTubePlayer; PlayerState: { PLAYING: number; PAUSED: number; ENDED: number } }; onYouTubeIframeAPIReady?: () => void } }
const songs: Song[] = [
  { id: 1, title: 'Aye Mere Humsafar', artist: 'Udit Narayan, Alka Yagnik', category: '90s Bollywood', duration: '05:51', color: '#f36b38', youtubeVideoId: 'NWCG3MUDc0A' },
  { id: 2, title: 'Pardesi Pardesi', artist: 'Udit Narayan, Alka Yagnik', category: '90s Bollywood', duration: '07:27', color: '#b62b35', youtubeVideoId: 'xKb6lP3JxrA' },
  { id: 3, title: 'Tu Cheez Badi Hai Mast Mast', artist: 'Udit Narayan, Kavita', category: 'Hindi Hits', duration: '05:58', color: '#f0b54d', youtubeVideoId: 'wEPZJQ6eAks' },
  { id: 4, title: 'Ghar Se Nikalte Hi', artist: 'Udit Narayan', category: 'Hindi Hits', duration: '07:38', color: '#507f72', youtubeVideoId: '0NT-xmLX4tk' },
  { id: 5, title: 'Tip Tip Barsa Paani', artist: 'Udit Narayan, Alka Yagnik', category: '90s Bollywood', duration: '05:53', color: '#8b4e9f', youtubeVideoId: 'BsrDrv4NV7M' },
  { id: 6, title: 'High Rated Gabru', artist: 'Guru Randhawa', category: 'Punjabi Highway', duration: '03:34', color: '#e65440', youtubeVideoId: 'hjWf8A0YNSE' },
];
const categories = [
  ['Punjabi Highway', '75+ songs', 'Full throttle beats for open roads', '🛣️'], ['Hindi Hits', '109 songs', 'Your familiar road-trip favorites', '🎶'], ['Bhojpuri Beats', '35 songs', 'Desi rhythm, mile after mile', '🌄'], ['90s Bollywood', '109 songs', 'Full-length Bollywood classics collection', '📻'], ['Sad & Romantic', '26 songs', 'Slow songs for the midnight drive', '🌙'], ['Desi Highway Mix', '109 songs', 'Every lane, every language, one mix', '🚚']
];
const playlistSongIds: Record<string, number[]> = {
  'Punjabi Highway': [6, 3],
  'Hindi Hits': [3, 4, 1],
  'Bhojpuri Beats': [2, 5],
  '90s Bollywood': [1, 2, 5, 4],
  'Sad & Romantic': [5, 1, 2],
  'Desi Highway Mix': [6, 3, 4, 5, 1, 2],
};
// Hosted YouTube playlists are used for long collections. The visible count matches the source playlist rather than a fake UI number.
const youtubePlaylistIds: Record<string, string> = {
  'Punjabi Highway': 'PL5WhpWFkannIKsNRVouRv-vFHM0szD_Fs',
  'Hindi Hits': 'PLo7WLtfSrhdYYdAM4UWSaUy4xG7_GZqXD',
  'Bhojpuri Beats': 'PL2oKEGroz3mz84Fy7tGtSjqXXkuJh2eue',
  '90s Bollywood': 'PLo7WLtfSrhdYYdAM4UWSaUy4xG7_GZqXD',
  'Desi Highway Mix': 'PLo7WLtfSrhdYYdAM4UWSaUy4xG7_GZqXD',
};
const youtubeCollectionVideos: Record<string, Song> = {
  'Sad & Romantic': { id: 99, title: 'Sad & Romantic — 26-song collection', artist: 'YouTube Music Collection', category: 'Sad & Romantic', duration: 'Full mix', color: '#44313b', youtubeVideoId: 'QcJnSKk02Os' },
};

export default function App() {
  const [active, setActive] = useState(songs[0]); const [playing, setPlaying] = useState(false); const [query, setQuery] = useState(''); const [menu, setMenu] = useState(false); const [progress, setProgress] = useState(0); const [currentTime, setCurrentTime] = useState(0); const [duration, setDuration] = useState(0); const [playerReady, setPlayerReady] = useState(false); const [queue, setQueue] = useState<Song[]>(songs); const [playlistName, setPlaylistName] = useState('All highway songs'); const [isYoutubePlaylist, setIsYoutubePlaylist] = useState(false); const [playlistPosition, setPlaylistPosition] = useState<number | null>(null); const [playlistTotal, setPlaylistTotal] = useState<number | null>(null);
  const youtubePlayer = useRef<YouTubePlayer | null>(null); const pendingSong = useRef<Song | null>(null); const pendingYoutubePlaylist = useRef<string | null>(null); const activeRef = useRef(active); const queueRef = useRef(queue); const isYoutubePlaylistRef = useRef(false); const playlistNameRef = useRef(playlistName);
  const formatTime = (seconds: number) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
  useEffect(() => { activeRef.current = active; }, [active]);
  useEffect(() => { queueRef.current = queue; }, [queue]);
  useEffect(() => { isYoutubePlaylistRef.current = isYoutubePlaylist; }, [isYoutubePlaylist]);
  useEffect(() => { playlistNameRef.current = playlistName; }, [playlistName]);
  useEffect(() => {
    const createPlayer = () => { youtubePlayer.current = new window.YT!.Player('youtube-player', { height: '1', width: '1', videoId: songs[0].youtubeVideoId, playerVars: { playsinline: 1, origin: window.location.origin }, events: { onReady: () => { setPlayerReady(true); }, onStateChange: (event: { data: number }) => { if (event.data === window.YT!.PlayerState.PLAYING) { setPlaying(true); if (isYoutubePlaylistRef.current) window.setTimeout(syncYoutubeTrack, 600); } if (event.data === window.YT!.PlayerState.PAUSED) setPlaying(false); if (event.data === window.YT!.PlayerState.ENDED && !isYoutubePlaylistRef.current) { const currentQueue = queueRef.current; const nextSong = currentQueue[(currentQueue.indexOf(activeRef.current) + 1) % currentQueue.length]; setActive(nextSong); youtubePlayer.current?.loadVideoById(nextSong.youtubeVideoId); } }, onError: () => { setPlaying(false); } } }); };
    if (window.YT?.Player) createPlayer(); else { window.onYouTubeIframeAPIReady = createPlayer; const script = document.createElement('script'); script.src = 'https://www.youtube.com/iframe_api'; script.async = true; document.head.appendChild(script); }
    return () => youtubePlayer.current?.destroy();
  }, []);
  useEffect(() => { const ticker = window.setInterval(() => { const player = youtubePlayer.current; if (!player || !playing) return; const time = player.getCurrentTime() || 0; const total = player.getDuration() || 0; setCurrentTime(time); setDuration(total); setProgress(total ? time / total * 100 : 0); }, 500); return () => window.clearInterval(ticker); }, [playing]);
  useEffect(() => { if (!playerReady) return; if (pendingYoutubePlaylist.current) { const id = pendingYoutubePlaylist.current; pendingYoutubePlaylist.current = null; youtubePlayer.current?.loadPlaylist({ list: id, listType: 'playlist' }); } else if (pendingSong.current) { const song = pendingSong.current; pendingSong.current = null; youtubePlayer.current?.loadVideoById(song.youtubeVideoId); } }, [playerReady, active]);
  const filtered = useMemo(() => songs.filter(s => `${s.title} ${s.artist} ${s.category}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const syncYoutubeTrack = () => { const player = youtubePlayer.current; if (!player) return; const data = player.getVideoData(); const playlist = player.getPlaylist(); if (data.video_id) setActive({ id: -1, title: data.title || 'Current playlist track', artist: data.author || 'YouTube Music', category: playlistNameRef.current, duration: 'Full track', color: '#8b4e9f', youtubeVideoId: data.video_id }); if (playlist?.length) { setPlaylistTotal(playlist.length); setPlaylistPosition(player.getPlaylistIndex() + 1); } };
  const choose = (song: Song, selectedQueue = queue, selectedPlaylist = playlistName) => { setIsYoutubePlaylist(false); isYoutubePlaylistRef.current = false; setPlaylistPosition(null); setPlaylistTotal(null); setQueue(selectedQueue); setPlaylistName(selectedPlaylist); setActive(song); setPlaying(true); setProgress(0); setCurrentTime(0); if (youtubePlayer.current) youtubePlayer.current.loadVideoById(song.youtubeVideoId); else pendingSong.current = song; };
  const startPlaylist = (title: string) => { const youtubePlaylist = youtubePlaylistIds[title]; if (youtubePlaylist) { const firstPlaylistSong = songs.find(song => song.category === title) ?? songs[0]; setQueue(songs.filter(song => song.category === title)); setActive(firstPlaylistSong); setPlaylistName(title); setIsYoutubePlaylist(true); isYoutubePlaylistRef.current = true; setPlaying(true); setProgress(0); setCurrentTime(0); if (youtubePlayer.current) { youtubePlayer.current.loadPlaylist({ list: youtubePlaylist, listType: 'playlist' }); window.setTimeout(syncYoutubeTrack, 900); } else pendingYoutubePlaylist.current = youtubePlaylist; return; } const collectionVideo = youtubeCollectionVideos[title]; if (collectionVideo) { choose(collectionVideo, [collectionVideo], title); return; } const selectedQueue = playlistSongIds[title].map(id => songs.find(song => song.id === id)!).filter(Boolean); choose(selectedQueue[0], selectedQueue, title); };
  const next = () => { if (isYoutubePlaylist) { youtubePlayer.current?.nextVideo(); window.setTimeout(syncYoutubeTrack, 700); } else choose(queue[(queue.indexOf(active) + 1) % queue.length], queue, playlistName); };
  const previous = () => { if (isYoutubePlaylist) { youtubePlayer.current?.previousVideo(); window.setTimeout(syncYoutubeTrack, 700); } else choose(queue[(queue.indexOf(active) - 1 + queue.length) % queue.length], queue, playlistName); };
  const seek = (value: number) => { setProgress(value); if (youtubePlayer.current && duration) { const time = duration * value / 100; youtubePlayer.current.seekTo(time, true); setCurrentTime(time); } };
  const togglePlayback = () => { if (!youtubePlayer.current) { pendingSong.current = active; return; } if (playing) youtubePlayer.current.pauseVideo(); else youtubePlayer.current.playVideo(); };
  return <><header><a className="brand" href="#top"><span>TW</span>Truck Wala <em>Music</em></a><nav><a href="#playlists">Playlists</a><a href="#songs">Songs</a><a href="#about">About</a><a href="#faq">FAQ</a></nav><button className="icon search-btn" aria-label="Search"><Search size={19}/></button><button className="icon mobile-menu" aria-label="Open menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<div className="drawer"><a href="#playlists">Playlists</a><a href="#songs">Songs</a><a href="#about">About</a></div>}</header>
  <main id="top"><section className="hero"><div className="hero-image"/><div className="hero-content"><p className="eyebrow"><span/> Truck Wala Music, one tap away</p><h1>The Indian truck driver playlist <i>for long roads.</i></h1><p className="intro">Punjabi, Hindi, Bhojpuri and classic Bollywood songs for every long highway journey.</p><div className="hero-actions"><button className="primary" onClick={()=>{choose(active); document.getElementById('now-playing')?.scrollIntoView({behavior:'smooth'})}}><Play fill="currentColor" size={18}/> Start listening</button><button className="secondary" onClick={()=>document.getElementById('playlists')?.scrollIntoView({behavior:'smooth'})}>Explore playlists <ChevronDown size={17}/></button></div><div className="hero-note"><Headphones size={16}/> Made for the miles that make the story</div></div></section>
  <section id="playlists" className="section"><div className="section-head"><div><p className="eyebrow">Pick your road</p><h2>Music for every <i>mood &amp; mile</i></h2></div><a href="#songs">View all <span>→</span></a></div><div className="category-grid">{categories.map(([title,count,detail,emoji],i)=><article className={`category cat-${i}`} key={title} onClick={()=>startPlaylist(title)}><div className="category-icon">{emoji}</div><div><p>{count}</p><h3>{title}</h3><small>{detail}</small></div><button aria-label={`Play ${title} playlist`} onClick={event=>{event.stopPropagation(); startPlaylist(title)}}><Play fill="currentColor" size={16}/></button></article>)}</div></section>
  <section id="songs" className="section songs-area"><div className="section-head"><div><p className="eyebrow">On the highway</p><h2>Popular this <i>week</i></h2></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search songs, artists..." aria-label="Search songs"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={16}/></button>}</div></div><div className="song-list">{filtered.length ? filtered.map((song,i)=><article className="song" key={song.id}><span className="num">{String(i+1).padStart(2,'0')}</span><div className="cover" style={{background:song.color}}><span>TW</span></div><div className="song-name"><h3>{song.title}</h3><p>{song.artist}</p></div><span className="tag">{song.category}</span><span className="duration"><Clock3 size={15}/>{song.duration}</span><button className="play-small" aria-label={`Play ${song.title}`} onClick={()=>choose(song)}>{active.id===song.id&&playing?<Pause fill="currentColor" size={16}/>:<Play fill="currentColor" size={16}/>}</button><button className="more" aria-label="Song options"><MoreHorizontal/></button></article>):<div className="empty">No songs found. Try another search.</div>}</div></section>
  <section id="about" className="about"><div><p className="eyebrow">Built for the journey</p><h2>More road. Less <i>fuss.</i></h2><p>Truck Wala Music is a browser-based Indian music playlist created for long roads, highway journeys and late-night drives.</p></div><div className="features"><div><b>01</b><h3>Made for the highway</h3><p>Simple controls designed for the long journey ahead.</p></div><div><b>02</b><h3>Desi songs in one mix</h3><p>Punjabi, Hindi, Bhojpuri and classic Bollywood.</p></div><div><b>03</b><h3>No account needed</h3><p>Open the site, choose a track, and get going.</p></div></div></section>
  <section id="faq" className="section faq"><p className="eyebrow">Questions from the road</p><h2>Good to <i>know</i></h2>{[['What is Truck Wala Music?','A browser-based playlist experience for Indian highway journeys.'],['Does it work on mobile?','Yes. The interface is responsive and optimized for mobile screens.'],['Where does the music play from?','Songs play through YouTube using the official YouTube player API.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section></main>
  <footer><a className="brand" href="#top"><span>TW</span>Truck Wala <em>Music</em></a><p>Made for long roads and desi journeys.</p><span>© 2026 Truck Wala Music</span></footer>
  <div id="youtube-player" className="youtube-frame" aria-hidden="true"/><aside id="now-playing" className="player"><div className="now-cover" style={{background:active.color}}>TW</div><div className="now-copy"><p>{playerReady ? `Playlist · ${playlistName}${playlistPosition && playlistTotal ? ` · ${playlistPosition}/${playlistTotal}` : ''}` : 'Loading player...'}</p><h3>{active.title}</h3><span>{active.artist} · {active.category}</span></div><div className="controls"><button aria-label="Previous song in playlist" onClick={previous}><SkipBack fill="currentColor"/></button><button className="big-play" aria-label={playing?'Pause':'Play'} onClick={togglePlayback}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button aria-label="Next song in playlist" onClick={next}><SkipForward fill="currentColor"/></button></div><div className="timeline"><span>{formatTime(currentTime)}</span><input aria-label="Playback progress" type="range" min="0" max="100" step="0.1" value={progress} onChange={e=>seek(+e.target.value)}/><span>{duration ? formatTime(duration) : active.duration}</span></div><div className="volume"><Volume2 size={18}/><input aria-label="Volume" type="range" defaultValue="70" onChange={e=>youtubePlayer.current?.setVolume(+e.target.value)}/></div><button className="youtube" onClick={()=>window.open(`https://www.youtube.com/watch?v=${active.youtubeVideoId}`,'_blank','noopener,noreferrer')}>Open on YouTube</button></aside></>;
}
